// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateJob(ctx context.Context, arg CreateJobParams) (Job, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteJob(ctx context.Context, id pgtype.UUID) error
	DeleteUser(ctx context.Context, id pgtype.UUID) error
	GetJob(ctx context.Context, id pgtype.UUID) (Job, error)
	GetUser(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	InsertJobLog(ctx context.Context, arg InsertJobLogParams) (JobLog, error)
	ListJobLogs(ctx context.Context, arg ListJobLogsParams) ([]JobLog, error)
	ListJobsByUser(ctx context.Context, arg ListJobsByUserParams) ([]Job, error)
	ListUsers(ctx context.Context) ([]User, error)
	UpdateJob(ctx context.Context, arg UpdateJobParams) (Job, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
